# Copyright (c) 2014, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('env')

libenv = env.Clone()

srcs = Glob('*.cc')
srcs.append(Glob('common/*.cc'))

# Platform specifics for common
if env['OS_GROUP'] == 'windows':
    srcs.append(Glob('common/os/windows/*.cc'))
else:
    srcs.append(Glob('common/os/posix/*.cc'))


libs = []

# Header files
libenv.Append(CPPPATH = ['.', '#inc'])

# Static library
objs = libenv.Object(srcs)
libs.append(libenv.StaticLibrary('alljoyn_ddapi', objs))

# Shared library
if libenv.get('LIBTYPE', 'static') != 'static':
    shobjs = libenv.SharedObject(srcs)
    libs.append(libenv.SharedLibrary('alljoyn_ddapi', shobjs))

Return ('libs')
